[package]
name = "Bangboo"
version = "0.1.0"
edition = "2024"

[dependencies]
twilight-cache-inmemory = { version = "0.16"}
twilight-gateway = { version = "0.16", features = ["simd-json", "native-tls"] }
twilight-http = { version = "0.16", features = ["simd-json"] }
twilight-model = { version = "0.16" }
twilight-util = { version = "0.16", features = ["full"] }
#THIDRPARTY
anyhow = { version = "1.0" }
ctrlc = { version = "3.4" }
chrono = { version = "0.4" }
colored = { version = "3" }
dotenvy = { version = "0.15" }
fast_image_resize = { version = "5.1" }
fontdue = { version = "0.9" }
image = { version = "0.25" }
once_cell = { version = "1.21" }
reqwest = { version = "0.12" }
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1" }
tiny-skia = { version = "0.11" }
tokio = { version = "1.44", features = ["rt-multi-thread"] }
