[package]
name = "Bangboo"
version = "0.2.9"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
twilight-cache-inmemory = { version = "0.16" }
twilight-gateway = { version = "0.16", features = ["zlib-stock", "native-tls"] }
twilight-http = { version = "0.16", features = ["native-tls"] }
twilight-model = { version = "0.16" }
twilight-util = { version = "0.16", features = ["full"] }
#THIDRPARTY
anyhow = { version = "1.0" }
chrono = { version = "0.4" }
colored = { version = "3" }
dotenvy = { version = "0.15" }
once_cell = { version = "1.21" }
reqwest = { version = "0.12" }
regex = { version = "1.11" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
skia-safe = { version = "0.84", features = ["textlayout"] }
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1" }
tokio = { version = "1.44", features = ["rt-multi-thread", "signal"] }
