[package]
name = "Bangboo"
version = "0.3.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
serenity = { version = "0.12", features = ["collector"] }
# THIRDPARTY
async-trait = { version = "0.1" }
anyhow = { version = "1.0" }
colored = { version = "3" }
dotenvy = { version = "0.15" }
once_cell = { version = "1.21" }
regex = { version = "1.11" }
reqwest = { version = "0.12" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
skia-safe = { version = "0.84", features = ["textlayout"] }
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1" }
tokio = { version = "1.44", features = ["rt-multi-thread", "signal"] }
chrono = { version = "0.4" }
