[package]
name = "Bangboo"
version = "0.1.0"
edition = "2024"

[dependencies]
twilight-cache-inmemory = { version = "0.16"}
twilight-gateway = { version = "0.16", features = ["simd-json"] }
twilight-http = { version = "0.16", features = ["simd-json"] }
twilight-model = { version = "0.16" }
twilight-util = { version = "0.16", features = ["full"] }
#THIDRPARTY
ctrlc = { version = "3.4"}
colored = { version = "3"}
skia-safe = { version = "0.82" }
dotenvy = { version = "0.15" }
once_cell = { version = "1.21" }
reqwest = { version = "0.12", features = ["blocking"] }
tokio = { version = "1.44", features = ["rt-multi-thread"] }
anyhow = { version = "1.0" }
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1" }
chrono = { version = "0.4" }
hex = "0.4.3"